export const testimonialData = [
    {
        id: 1,
        desc: "This product has changed my life! The best purchase I've made in years.",
        img: "https://randomuser.me/api/portraits/men/1.jpg",
        name: "John Doe",
        role: "CEO",
        company: "TechCorp",
        rating: 5,
    },
    {
        id: 2,
        desc: "Excellent customer service, and the quality is top-notch!",
        img: "https://randomuser.me/api/portraits/women/2.jpg",
        name: "Jane Smith",
        role: "Marketing Manager",
        company: "MarketPro",
        rating: 4,
    },
    {
        id: 3,
        desc: "I would highly recommend this to anyone looking to improve their workflow.",
        img: "https://randomuser.me/api/portraits/men/3.jpg",
        name: "David Johnson",
        role: "Software Engineer",
        company: "DevWorks",
        rating: 4.5,
    },
    {
        id: 4,
        desc: "Absolutely love it! A game-changer for our business operations.",
        img: "https://randomuser.me/api/portraits/women/4.jpg",
        name: "Emily Davis",
        role: "Product Manager",
        company: "InnovateTech",
        rating: 5,
    },
    {
        id: 5,
        desc: "Great quality at an affordable price. Will definitely buy again!",
        img: "https://randomuser.me/api/portraits/men/5.jpg",
        name: "Michael Brown",
        role: "Designer",
        company: "DesignLab",
        rating: 4,
    },
    {
        id: 6,
        desc: "This exceeded my expectations. Highly professional service!",
        img: "https://randomuser.me/api/portraits/women/6.jpg",
        name: "Olivia White",
        role: "Content Creator",
        company: "Creative Solutions",
        rating: 5,
    },
    {
        id: 7,
        desc: "Fantastic experience from start to finish. Highly recommend!",
        img: "https://randomuser.me/api/portraits/men/7.jpg",
        name: "Daniel Green",
        role: "Sales Director",
        company: "GlobalReach",
        rating: 4.5,
    },
    {
        id: 8,
        desc: "Top-notch service and an amazing product. Truly impressed.",
        img: "https://randomuser.me/api/portraits/women/8.jpg",
        name: "Sophia Harris",
        role: "HR Manager",
        company: "Harris Enterprises",
        rating: 5,
    },
];